#!/usr/bin/env zsh

source="../.."
target_base=/run/media/manjaro
target1="$target_base/BACKUP/home"
target2="$target_base/BIGDATA/backups/home"
 
print "Backup Home Folder"
print "backup 1 ==> '$source' -> '$target1"
print "backup 2 ==> '$source' -> '$target2"
sudo rsync -rlpth --mkpath --chown=1000:1000 --delete --verbose --progress --exclude={'.android','.cargo','.cache','.npm','.yarn'} $source $target1
sudo rsync -rlpth --mkpath --chown=1000:1000 --delete --verbose --progress --exclude={'.android','.cargo','.cache','.npm','.yarn'} $source $target2
