#!/usr/bin/env zsh

TARGET="$1"
EXCLUDES="--exclude={'*/.android/', '*/.cargo/', '*/.cache/', '*/.npm/', '**/.yarn/**', '**/node_modules/**'}"

echo "Target...: $TARGET"
echo "Excludes.: $EXCLUDES"

SOURCES=

for SOURCE in \
	/media/WORKSPACE \
	/srv \
	/home/$USER \
	/media/BIGDATA \
	/media/VM
do
	if [ -x "$SOURCE" ]; then
		pushd $SOURCE
		print "Backup $SOURCE -> $TARGET"
		# print "sudo rsync -av --delete $EXCLUDES $SOURCE $TARGET --delete-excluded --ignore-errors"
		sudo rsync $EXCLUDES $SOURCE $TARGET -arv --delete --delete-excluded --ignore-errors
		# sudo rsync -av --delete --exclude=swapfile --exclude=docker/ /srv /run/media/ralf/56f60d5e-4d58-4b63-9eea-add952c105a2/
		popd
	fi
done
