#!/usr/bin/env bash

MOUNT_BASE="/media"

for PART in \
"BACKUP" \
"BIGDATA" \
"VM" \
"WORKSPACE"
do
    NAMED_PART="/dev/disk/by-partlabel/$PART"
    MOUNT_PART="$MOUNT_BASE/$PART"
    
    if [ -b "$NAMED_PART" ]; then
        echo "Unmount Crypted PARTITION $NAMED_PART"
        sudo umount -v "$MOUNT_PART"

        echo "Close Crypted PARTITION $PART"
        sudo cryptsetup -v close "$PART"
        
        echo "Open Crypted PARTITION $PART"
        sudo cryptsetup -v open $NAMED_PART $PART --key-file /crypto_keyfile.bin        
    fi
done

sudo micro /etc/crypttab /etc/fstab

echo "Reload Mount-Daemon."
sudo systemctl daemon-reload

echo "Mount all Partitons."
sudo mount --all
