#!/usr/bin/env zsh

echo "
# Custom LUKS
WORKSPACE   /dev/disk/by-partlabel/WORKSPACE    /crypto_keyfile.bin luks
BACKUP      /dev/disk/by-partlabel/BACKUP       /crypto_keyfile.bin luks
BIGDATA     /dev/disk/by-partlabel/BIGDATA      /crypto_keyfile.bin luks
VM          /dev/disk/by-partlabel/VM           /crypto_keyfile.bin luks
" | sudo tee -a /etc/crypttab

sudo micro /etc/crypttab

echo "
# Custom Mounts
/dev/mapper/WORKSPACE	/media/WORKSPACE	ext4    defaults,noatime 0 2
/dev/mapper/BACKUP		/media/BACKUP		ext4    defaults,noatime 0 2
/dev/mapper/BIGDATA		/media/BIGDATA		ext4    defaults,noatime 0 2
/dev/mapper/VM          /media/VM           ext4    defaults,noatime 0 2
" | sudo tee -a /etc/fstab

sudo micro /etc/fstab

sudo systemctl daemon-reload
sudo mount --all
