#!/usr/bin/env bash

# shellcheck source=./config
source ./config

sudo podman network create $network

sudo podman run \
    -dit \
    --privileged \
    --name $container_name \
    -e "ACCEPT_EULA=Y" \
    -e "MSSQL_PID=developer" \
    -e "MSSQL_SA_PASSWORD=$sa_password" \
    -e "SA_PASSWORD=$sa_password" \
    -p 1433:1433 \
    -v $data_dir:/var/opt/mssql \
    -d $image_name

# Docker Prozesse prüfen
sudo podman ps -a

echo "sa Passwort: $sa_password"

# echo "Logge: $container_name"
# sudo podman logs -f --tail 100 $container_name
