#!/usr/bin/env bash

# shellcheck source=./config
source "$HOME/.scripts/helper/mssql/config"

sudo podman run \
    -dit \
    --restart always \
    --privileged \
    --name $container_name \
    -e "ACCEPT_EULA=Y" \
    -e "SA_PASSWORD=$sa_password" \
    -p 1433:1433 \
    -v $data_dir:/var/opt/mssql \
    -v $data_dir/$conf_file:/var/opt/mssql/$conf_file \
    -v $data_dir/$cert_pem_file:/etc/ssl/certs/$cert_pem_file \
    -v $data_dir/$cert_key_file:/etc/ssl/private/$cert_key_file \
    -d $image_name

# Docker Prozesse prüfen
sudo podman ps -a

echo "Logge: $container_name"
sudo podman logs -f --tail 100 $container_name
