#!/usr/bin/env bash

# shellcheck source=./config
source "$HOME/.scripts/helper/mssql/config"

echo "Aktuell installierte Container:"
sudo podman container ls

echo "Logge: $container_name"
sudo podman logs -f --tail 100 $container_name
