#!/usr/bin/env bash

# shellcheck source=./config
source ./config

# Ziel Ordner für volume vorbereiten
if [ -d "$data_dir" ]; then
    echo "mssql datadir '$data_dir' exists, reuse it."
else
    echo "mssql datadir '$data_dir' does not exists, create it!"
    sudo mkdir -p $data_dir
fi

# sudo rm -fr $data_dir/.system
# sudo mkdir -p $data_dir/.system
sudo chown 10001:root -R $data_dir
sudo chmod -R 'u=rwx,o=rwx,g=rwx' $data_dir
