#!/usr/bin/env bash

# shellcheck source=./config
source "$HOME/.scripts/helper/mssql/config"

echo "Aktuell installierte Container:"
sudo podman container ls

echo "Stoppe: $container_name"
sudo podman container stop $container_name

echo "Entferne: $container_name"
sudo podman container prune --force

echo "Aktuell installierte Container:"
sudo podman container ls

# delete old folders
sudo rm -fr $data_dir/.system
sudo rm -fr $data_dir/secrets
sudo rm -fr $data_dir/mssql.*
