#!/usr/bin/env bash

# shellcheck source=./config
source "$HOME/.scripts/helper/mssql/config"

echo "Aktuell installierte Container:"
sudo podman container ls

echo "Stoppe: $container_name"
sudo podman container stop $container_name
