#!/usr/bin/env bash

# shellcheck source=./config
source "$HOME/.scripts/helper/mssql/config"

echo "Aktuell installierte Container:"
sudo podman container ls

echo "Stoppe service: $container_name.service"
sudo systemctl stop --now $container_name.service
