# code: language=ansible
---
- name: DefineBaseSystemPackages
  vars:
    global_init:
      # global
      - acpi
      - acpid
      - ansible-lint
      - arandr
      - arj
      - ark
      - at
      - bat
      - blueman
      - bpytop
      - brightnessctl
      - clamav
      - clamtk
      - copyq
      - cronie
      - curl
      - dex
      - dnsutils
      - docker
      - docker-compose
      - dpkg
      - exa
      - feh
      - flameshot
      - fzf
      - glances
      - gnome-keyring
      - gparted
      - gpick
      - grc
      - gvfs-smb
      - htop
      - iftop
      - inotify-tools
      - iotop
      - iptraf-ng
      - jq
      - kitty
      - kteatime
      - libgnome-keyring
      - libsecret
      - light
      - lsd
      - lxsession
      - mpv
      - multitail
      - ncmpcpp
      - nitrogen
      - numlockx
      - openconnect
      - openssh
      - p7zip
      - picom
      - python-mutagen
      - qbittorrent
      - rofi
      - scrot
      - stow
      - sysstat
      - time
      - timeshift
      - toilet
      - unclutter
      - unrar
      - upower
      - wmctrl
      - xautolock
      - xbindkeys
      - xclip
      - xdotool
      - xscreensaver
      - xsel

      # system tools
      - grub-customizer

      # Python libs
      - python
      - python-pip

      # utils for editors
      - bash-completion
      - clang
      - gdb

      # config tools
      - lxappearance

      # utilities from gnome
      - gnome-disk-utility
      - gnome-system-monitor
      - gnome-system-log
      - gnome-logs
      - gnome-calculator
      - network-manager-applet

      - qt5ct

      # file manager
      - mc
      - ranger

      # useful tools for ranger
      - elinks
      - highlight
      - highlight-gui
      - libcaca
      - lynx
      - mediainfo
      - odt2txt
      - poppler
      - w3m

      # Nemo
      - cinnamon-translations
      - gtkhash-nemo
      - nemo
      - nemo-audio-tab
      - nemo-compare
      - nemo-emblems
      - nemo-fileroller
      - nemo-image-converter
      - nemo-preview
      - nemo-seahorse

      # other
      - rofi
      - rofimoji
      - bleachbit

      # bluetooth
      - blueman

      # printer setup
      - cups-pdf
      - foomatic-db
      - foomatic-db-ppds
      - ghostscript
      - gutenprint
      - hplip
      - system-config-printer

      # utils for editors
      - bash-completion
      - clang
      - gdb
      - graphviz
      - shellcheck

      # language files
      - man-pages-de
      - aspell-de
      - mythes-de

    archlinux_based_init:
      # global
      - ansible-language-server
      - glfw-x11

      - base-devel
      - xinit-xsession

      # system tools
      - grub-btrfs
      - partitionmanager
      - update-grub

      # utilities from gnome
      - gnome-system-tools

      # QT Tools
      - qt5gtk2
      - qt5-styleplugins
      - gtk-engine-murrine
      
      # useful tools for ranger
      - atool
      - atool-desktop
      - ffmpegthumbnailer
      - imagemagick
      - ueberzug

      # file manager
      - ranger_devicons-git

      # Nemo
      - nemo-media-columns
      - nemo-mediainfo-tab
      - nemo-qml-plugin-notifications
      - nemo-share

      # printer setup
      - brother-mfc-j4420dw
      - canon-cque
      - foomatic-db-engine
      - foomatic-db-gutenprint-ppds
      - foomatic-db-nonfree
      - foomatic-db-nonfree-ppds
      - gsfonts
      - print-manager
      
      # installation of important editors
      - micro
      - aur/visual-studio-code-bin

      # system packages
      - bitwarden
      - eject-applet
      - hardinfo
      - ibus-daemon
      - luacheck
      - networkmanager
      - networkmanager-openconnect
      - notify-send.sh
      - oh-my-posh-bin
      - packagekit
      - picom
      - pm-utils
      - powershell-bin
      - shell-color-scripts
      - system-monitoring-center
      - watchexec
      - wezterm
      - xorg-server-xephyr
      - xorg-xbacklight
      - xorg-xfd
      - xorg-xrandr
      - xorg-xsetroot

      # polkits
      - polkit
      - polkit-gnome

      # sound setup
      - alsa-oss
      - alsa-utils
      - livecd-sounds
      - pamixer
      - paprefs
      - pasystray
      - pavucontrol
      - pnmixer
      - ponymix
      - sound-theme-smooth
      - sp
      - tvolnoti

      # lightdm config
      - lightdm
      - lightdm-settings
      - lightdm-gtk-greeter-settings
      - lightdm-gtk-greeter
      - lightdm-slick-greeter

      # language files
      - languagetool

    fedora_based_init:
      - xorg-x11-xinit-session
      - i-nex
      - xset

      # system tools
      - kde-partitionmanager
      - inotify-tools

      # printer setup
      - kde-print-manager
      - printer-driver-brlaser
      - foomatic
      - foomatic-db
      - foomatic-db-ppds

      # file manager
      - vim-devicons

    arcolinux_init:
      - arcolinux-config-awesome-git

      # Meta Packages
      - arcolinux-meta-log
      - arcolinux-meta-logout
      - arcolinux-meta-fun
      - arcolinux-meta-samba
      - arcolinux-meta-utilities

      # Rofi Configs
      - arcolinux-rofi-git
      - arcolinux-rofi-themes-git
      - rofi-themes
      - rofi-theme-fonts

    manjaro_init:
      - samba
      - manjaro-settings-samba

      # sound setup
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - pulseaudio-equalizer

      # bluetooth
      - manjaro-bluetooth

      # printer setup
      - manjaro-printer

      # other Metas
      - plasma-meta
      - xfce4-meta

  include_tasks: lib/install.yml
