---
- name: set powerline fonts in vconsole
  ansible.builtin.lineinfile:
    path: /etc/vconsole.conf
    regexp: '^FONT='
    line: FONT=ter-powerline-v12n

- name: xdg default setzen
  command: xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search

- name: grub config
  block:
    - name: gfxmodes
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^.*GRUB_GFXMODE='
        line: 'GRUB_GFXMODE="3840x2160,2560x1080,1920x1080,auto'

    - name: terminal output
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^.*GRUB_TERMINAL_OUTPUT='
        line: '#GRUB_TERMINAL_OUTPUT="console'

    - name: terminal input
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^.*GRUB_TERMINAL_INPUT='
        line: '#GRUB_TERMINAL_INPUT="console'

    - name: theme
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^.*GRUB_TERMINAL_INPUT='
        line: '#GRUB_TERMINAL_INPUT="console'

    - set_fact:
        grub: "{{ lookup('file', '/etc/default/grub') }}"

    - debug: var=grub

    - name: update
      command: grub2-mkconfig --output=/boot/grub2/grub.cfg
      when: is_rhel_based

    - name: grub-update
      shell: |
        mkinitcpio -P
        grub-mkconfig -o /boot/grub/grub.cfg
      when: is_arch_based

- name: add HP MFP 178/179 Printer Model
  ansible.builtin.blockinfile:
    path: /etc/issue
    block: |
      \e[H\e[2J
                                                                 \e[1;30m| \e[34m\r \s
             \e[36;1m/\\\\                        \e[37m||      \e[36m| =                 \e[30m|
            \e[36m/  \\\\                       \e[37m||      \e[36m|                   \e[30m| \e[32m\t
           \e[1;36m/ \e[0;36m.. \e[1m\\\\   \e[37m//==\\\\\\ ||/= /==\\\\ ||/=\\\\  \e[36m| | |/\\\\ |  | \\\\ /  \e[30m| \e[32m\d
          \e[0;36m/ .  . \\\\ \e[37m||    || ||  ||     ||  ||  \e[36m| | |  | |  |   X   \e[1;30m|
         \e[0;36m/  .  .  \\\\ \e[37m\\\\\\==/| ||   \\\\==/ ||  ||  \e[36m| | |  |\  \\/|  / \\\\ \e[1;30m| \e[31m\U
        \e[0;36m/ ..    .. \\\\   \e[0;37mA simple, lightweight linux distribution.   \e[1;30m|
       \e[0;36m/_'        `_\\\\                                              \e[1;30m| \e[35m\l \e[0mon \e[1;33m\n
      \e[0m
