---
- hosts: localhost
  connection: local
  name: "==========> Install Grub Layout and Settings <=========="
  become: true

  # install galaxy roles
  roles:
    - role: robertdebock.bootstrap

  vars:
    is_dry: false

    is_arch_based: false
    is_arch: false
    is_arcolinux: false
    is_manjaro: false

    is_rhel_based: false
    is_rhel: false
    is_fedora: false
    is_centos: false

    is_debian_based: false
    is_debian: false
    is_ubuntu: false

    grub_theme: 13

  tasks:
    - name: "=====> Initiate <====="
      ansible.builtin.include_tasks: lib/inits.yml

    - name: "=====> Post Installation Finishing <====="
      ansible.builtin.include_tasks: lib/grub.yml
