---
- hosts: localhost
  connection: local
  name: "==========> Install Grub Layout and Settings <=========="
  become: true

  # install galaxy roles
  roles:
    - role: robertdebock.bootstrap

  vars:
    grub_theme: 13

  tasks:
    - name: "=====> Initiate <====="
      include_tasks: lib/inits.yml

    - name: "=====> Post Installation Finishing <====="
      include_tasks: lib/grub.yml
