---
- name: set powerline fonts in vconsole
  ansible.builtin.lineinfile:
    path: /etc/vconsole.conf
    regexp: '^FONT='
    line: FONT=ter-powerline-v12n

- name: xdg default setzen
  command: xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search

- name: grub config
  block:
    - name: gfxmodes
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^.*GRUB_GFXMODE='
        line: 'GRUB_GFXMODE="3840x2160,2560x1080,1920x1080,auto'

    - name: terminal output
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^.*GRUB_TERMINAL_OUTPUT='
        line: '#GRUB_TERMINAL_OUTPUT="console'

    - name: terminal input
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^.*GRUB_TERMINAL_INPUT='
        line: '#GRUB_TERMINAL_INPUT="console'

    - name: theme
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^.*GRUB_TERMINAL_INPUT='
        line: '#GRUB_TERMINAL_INPUT="console'

    - set_fact:
        grub: "{{ lookup('file', '/etc/default/grub') }}"

    - debug: var=grub

    - name: update
      command: grub2-mkconfig --output=/boot/grub2/grub.cfg
      when: is_rhel_based

    - name: grub-update
      shell: |
        mkinitcpio -P
        grub-mkconfig -o /boot/grub/grub.cfg
      when: is_arch_based

- name: write issue file
  ansible.builtin.blockinfile:
    path: /etc/issue
    create: true
    block: |      
      1: \e[37mWelcome to Fedora!
      2: \e[34m\r \s 
      3: \e[32m\t 
      4: \e[32m\d 
      5: \e[31m\U 
      6: \e[35m\l \e[0mon \e[1;33m
      7: \v
      8: \o
