---
- hosts: localhost
  connection: local
  name: "==========> Install Test <=========="
  become: false

  vars:
    is_dry: false
    
    is_arch_based: false
    is_arch: false
    is_arcolinux: false
    is_manjaro: false

    is_rhel_based: false
    is_rhel: false
    is_fedora: false
    is_centos: false

    is_debian_based: false
    is_debian: false
    is_ubuntu: false

    is_suse_based: false
    is_tumble: false

  tasks:
    - name: "=====> Initiate <====="
      include_tasks: lib/inits.yml

#    - name: "=====> Pre Installation Prepare <====="
#      include_tasks: lib/prepare.yml

    - name: Install requirements and dependencies
      vars:
        rhel_based_init:
          - bison
          - ccache
          - ctags 
          - flex
          - gcc 
          - gcc-c++
          - git 
          - libXi-devel
          - make
          - ncurses-devel 
          - openssl-devel
          - qt3-devel
    
      include_tasks: lib/install.yml
