---
- hosts: localhost
  connection: local
  name: "==========> Install Test <=========="
  become: false

  tasks:
    - name: "=====> Initiate <====="
      include_tasks: lib/inits.yml

#    - name: "=====> Pre Installation Prepare <====="
#      include_tasks: lib/prepare.yml

    - name: Install requirements and dependencies
      vars:
        rhel_based_init:
          - bison
          - ccache
          - ctags 
          - flex
          - gcc 
          - gcc-c++
          - git 
          - libXi-devel
          - make
          - ncurses-devel 
          - openssl-devel
          - qt3-devel
    
      include_tasks: lib/install.yml
