---
- hosts: localhost
  connection: local
  name: "==========> Install Tenvans Dotfiles with AwesomeWm Desktop <=========="
  become: yes

  # install galaxy roles
  # roles:
   # - role: robertdebock.bootstrap
   # - role: robertdebock.rpmfusion

  vars:
    is_dry: false
    is_rhel_based: false
    is_arch_based: false
    is_arcolinux: false
    is_manjaro: false
    is_rhel: false
    is_fedora: false
    is_centos: false
    grub_theme: 1
    fedora_init:
      - akmod-nvidia

  tasks:
    - name: "=====> Initiate <====="
      include_tasks: lib/inits.yml

    - name: fedora nvidia
      block:
      
        - name: install nvidia driver
          include_tasks: lib/install.yml

        - name: remove nouveau driver    
          ansible.builtin.blockinfile:
            path: /etc/modprobe.d/blacklist-nouveau.conf
            create: true
            block: |      
              blacklist nouveau
              options nouveau modeset=0

        - name: backup old initramfrs
          shell: mv /boot/initramfs-$(uname -r).img /boot/initramfs-$(uname -r)-nouveau.img

        - name: create new initramfrs with nvidia
          shell: sudo dracut /boot/initramfs-$(uname -r).img $(uname -r)  

      when: is_fedora    
