---
- hosts: localhost
  connection: local
  name: "==========> Install Plasma Desktop <=========="
  become: true

  tasks:
    - name: "=====> Initiate <====="
      include_tasks: lib/inits.yml

    - name: "=====> Pre Installation Prepare <====="
      include_tasks: lib/prepare.yml

    - name: "==== get EPEL Paket"
      shell: |
        wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        sudo dnf install epel-release-latest-8.noarch.rpm
        sudo dnf update -y
        sudo dnf install @kde-desktop --allowerasing --nobest --skip-broken -y
