---
- hosts: localhost
  connection: local
  name: "==========> Install Tenvans Dotfiles with AwesomeWm Desktop <=========="
  become: true

  tasks:
    - name: "=====> Initiate <====="
      include_tasks: lib/inits.yml

    - name: Ad user to sudoers 
      community.general.sudoers:
        name: 100-myrules
        state: present
        user: "{{ user_id }}"
        commands: ALL
        runas: ALL
        nopassword: true
