---
- hosts: localhost
  connection: local
  name: "==========> Install Tenvans Dotfiles with AwesomeWm Desktop <=========="
  become: yes

  vars:
    is_dry: false
    is_rhel_based: false
    is_arch_based: false
    is_arcolinux: false
    is_manjaro: false
    is_rhel: false
    is_fedora: false
    is_centos: false
    
  tasks:
    - name: "=====> Initiate <====="
      include_tasks: lib/inits.yml

    - name: Allow the backup user to sudo /usr/local/bin/backup
      community.general.sudoers:
        name: 100-myrules
        state: present
        user: "{{ user_id }}"
        commands: ALL
        runas: ALL
        nopassword: true
