---
- hosts: localhost
  connection: local
  name: "==========> Install Tenvans Dotfiles with AwesomeWm Desktop <=========="
  become: true

  vars:
    is_dry: false
    is_arch_based: false
    is_arch: false
    is_arcolinux: false
    is_manjaro: false

    is_rhel_based: false
    is_rhel: false
    is_fedora: false
    is_centos: false

    is_debian_based: false
    is_debian: false
    is_ubuntu: false

    is_suse_based: false
    is_tumble: false

  tasks:
    - name: "=====> Initiate <====="
      include_tasks: lib/inits.yml

    - name: Ad user to sudoers 
      community.general.sudoers:
        name: 100-myrules
        state: present
        user: "{{ user_id }}"
        commands: ALL
        runas: ALL
        nopassword: true
