---
- hosts: localhost
  connection: local
  name: "==========> Install Tenvans Dotfiles with AwesomeWm Desktop <=========="
  become: true

  # install galaxy roles
  roles:
    - role: robertdebock.bootstrap

  vars:
    grub_theme: 13

  tasks:
    - name: "=====> Initiate <====="
      include_tasks: lib/inits.yml

    - name: "=====> Pre Installation Prepare <====="
      include_tasks: lib/prepare.yml

    - name: "=====> Install System Development Packages <====="
      include_tasks: lib/system-develop.yml

    - name: "=====> Install System Base Packages <====="
      include_tasks: lib/system-base.yml
      
    - name: "=====> Post Installation Finishing <====="
      include_tasks: lib/grub.yml

    - name: "=====> Post Installation Finishing <====="
      include_tasks: lib/system-finish.yml
