---
- hosts: localhost
  connection: local
  name: "==========> Install Test <=========="
  become: true

  tasks:
    - name: "=====> Initiate <====="
      include_tasks: lib/inits.yml

    - name: "=====> Pre Installation Prepare <====="
      include_tasks: lib/prepare.yml

    - name: Define testing packages
      vars:
        global_init:
          # - google-chrome

      include_tasks: lib/install.yml
