---
- hosts: localhost
  connection: local
  name: "==========> Install Test <=========="
  become: true

  vars:
    is_dry: true
    
  tasks:
    - name: "=====> Initiate <====="
      include_tasks: lib/inits.yml

    # - name: "=====> Pre Installation Prepare <====="
    #   include_tasks: lib/prepare.yml
