---
- hosts: localhost
  connection: local
  name: "==========> Install Tenvans Dotfiles with AwesomeWm Desktop <=========="
  become: false

  tasks:
    - name: "=====> Initiate <====="
      include_tasks: lib/inits.yml

    - name: "=====> Post Installation Finishing <====="
      include_tasks: lib/displays.yml
      when: lookup('env', 'DOCKER_CONTAINER') != "true"
