---
- hosts: localhost
  connection: local
  name: "==========> Install Tenvans Dotfiles with AwesomeWm Desktop <=========="
  become: true

  vars:
    is_dry: false

    is_arch_based: false
    is_arch: false
    is_arcolinux: false
    is_manjaro: false

    is_rhel_based: false
    is_rhel: false
    is_fedora: false
    is_centos: false

    is_debian_based: false
    is_debian: false
    is_ubuntu: false

  tasks:
    - name: "=====> Initiate <====="
      ansible.builtin.include_tasks: lib/inits.yml

    - name: "=====> Pre Installation Prepare <====="
      ansible.builtin.include_tasks: lib/prepare.yml

    - name: "=====> Install System Development Packages <====="
      ansible.builtin.include_tasks: lib/develop-workstation.yml

    - name: "=====> Install Workstation Base Packages <====="
      ansible.builtin.include_tasks: lib/base-workstation.yml

    - name: "=====> Install Workstation Layout Packages <====="
      ansible.builtin.include_tasks: lib/layout-workstation.yml

    - name: "=====> Install Apps <====="
      ansible.builtin.include_tasks: lib/apps.yml

    - name: "=====> Post Installation Finishing <====="
      ansible.builtin.include_tasks: lib/displays.yml

    - name: "=====> Post Installation Finishing <====="
      ansible.builtin.include_tasks: lib/finish-workstation.yml
