---
- hosts: localhost
  connection: local
  name: "==========> Install Tenvans Dotfiles with AwesomeWm Desktop <=========="
  become: true

  vars:
    is_dry: false

    is_arch_based: false
    is_arch: false
    is_arcolinux: false
    is_manjaro: false

    is_rhel_based: false
    is_rhel: false
    is_fedora: false
    is_centos: false

    is_debian_based: false
    is_debian: false
    is_ubuntu: false

    is_suse_based: false
    is_tumble: false

  tasks:
    - name: "=====> Initiate <====="
      include_tasks: lib/inits.yml

    - name: "=====> Pre Installation Prepare <====="
      include_tasks: lib/prepare.yml

    - name: "=====> Install System Development Packages <====="
      include_tasks: lib/workstation-develop.yml

    - name: "=====> Install Workstation Base Packages <====="
      include_tasks: lib/workstation-base.yml

    - name: "=====> Install Workstation Layout Packages <====="
      include_tasks: lib/workstation-layout.yml

    - name: "=====> Install Vms Packages <====="
      include_tasks: lib/workstation-vm.yml

    - name: "=====> Install Apps <====="
      include_tasks: lib/apps.yml

    - name: "=====> Post Installation Finishing <====="
      include_tasks: lib/workstation-finish.yml
