---
- hosts: localhost
  connection: local
  name: "==========> Install Tenvans Dotfiles with AwesomeWm Desktop <=========="
  become: true

  tasks:
    - name: "=====> Initiate <====="
      include_tasks: lib/inits.yml

    - name: "=====> Pre Installation Prepare <====="
      include_tasks: lib/prepare.yml

    - name: "=====> Install System Development Packages <====="
      include_tasks: lib/workstation-develop.yml

    - name: "=====> Install Workstation Base Packages <====="
      include_tasks: lib/workstation-base.yml

    - name: "=====> Install Workstation Layout Packages <====="
      include_tasks: lib/workstation-layout.yml

    - name: "=====> Post Installation Finishing <====="
      include_tasks: lib/workstation-finish.yml
