#!/usr/bin/env bash
#
# LightDM wrapper to run around X sessions.

echo "Running X session wrapper"

# Load profile
echo "Loading .profile files";
for file in "/etc/profile" "$HOME/.profile" "$HOME/.profile-custom" "/etc/xprofile" "$HOME/.xprofile" "$HOME/.xprofile-custom"; do
    if [ -f "$file" ]; then
        echo "Loading profile from $file";
        . "$file"
    fi
done

# Load resources
echo "Loading .Xresource files";
for file in "/etc/X11/Xresources" "$HOME/.Xresources" "$HOME/.Xresources-custom"; do
    if [ -f "$file" ]; then
        echo "Loading resource: $file"
        xrdb -merge "$file"
    fi
done

# Load keymaps
echo "Loading .Xkbmap files";
for file in "/etc/X11/Xkbmap" "$HOME/.Xkbmap" "$HOME/.Xkbmap-custom"; do
    if [ -f "$file" ]; then
        echo "Loading keymap: $file"
        setxkbmap `cat "$file"`
        XKB_IN_USE=yes
    fi
done

# Load xmodmap if not using XKB
echo "Loading .Xmodmap files";
if [ -z "$XKB_IN_USE" ]; then
    for file in "/etc/X11/Xmodmap" "$HOME/.Xmodmap" "$HOME/.Xmodmap-custom"; do
        if [ -f "$file" ]; then
           echo "Loading modmap: $file"
           xmodmap "$file"
        fi
    done
fi

unset XKB_IN_USE

# Run all system xinitrc shell scripts
echo "Loading .xinitrc.d files";
xinitdir="/etc/X11/xinit/xinitrc.d"
if [ -d "$xinitdir" ]; then
    for script in $xinitdir/*; do
        echo "Loading xinit script $script"
        if [ -x "$script" -a ! -d "$script" ]; then
            . "$script"
        fi
    done
fi

# Run user xsession shell script
echo "Loading .xsession files";
for file in "$HOME/.xsession" "$HOME/.xsession-custom"; do
    if [ -f "$file" ]; then
        echo "Loading xsession from $file";
        . "$file"
    fi
done

echo "X session wrapper complete, running session $@"

SESSION=${1:-awesome}

get_session(){
	local dbus_args=(--sh-syntax --exit-with-session)
	case "$1" in
		awesome) dbus_args+=(awesome) ;;
		bspwm) dbus_args+=(bspwm-session) ;;
		budgie) dbus_args+=(budgie-desktop) ;;
		cinnamon) dbus_args+=(cinnamon-session) ;;
		deepin) dbus_args+=(startdde) ;;
		enlightenment) dbus_args+=(enlightenment_start) ;;
		fluxbox) dbus_args+=(startfluxbox) ;;
		gnome) dbus_args+=(gnome-session) ;;
		i3|i3wm) dbus_args+=(i3 --shmlog-size 0) ;;
		jwm) dbus_args+=(jwm) ;;
		kde) dbus_args+=(startplasma-x11) ;;
		lxde) dbus_args+=(startlxde) ;;
		lxqt) dbus_args+=(lxqt-session) ;;
		mate) dbus_args+=(mate-session) ;;
		xfce) dbus_args+=(xfce4-session) ;;
		openbox) dbus_args+=(openbox-session) ;;
		sway) dbus_args+=(sway --my-next-gpu-wont-be-nvidia) ;;
		*) dbus_args+=("$1") ;;
	esac

	echo "dbus-launch ${dbus_args[*]}"
	# echo "${dbus_args[*]}"
}

LAUNCHER=$(get_session "$SESSION")

echo "Launch: $LAUNCHER"
exec $LAUNCHER
