#!/usr/bin/env bash

. ~/.scripts/defs
. ~/.bin/audio-test

ponymix set-default --sink -d "$SINK_NEXT"

playsound device-changed &
notify-send "Next Sound Card" "$CARD_NEXT"

VOL=$(ponymix get-volume)
MUTE=$(amixer get Master | grep -Po "\[off\]" | tail -1)

echo "Vol: $VOL | Mute: $MUTE"
