#!/usr/bin/env bash

. ~/.scripts/defs
. ~/.bin/audio-test

ponymix set-default --sink -d "$SINK_PREV"

playsound device-changed &
notify-send "Prev Sound Card" "$CARD_PREV"

VOL=$(amixer get Master | grep -Po "[0-9]+(?=%)" | tail -1)
MUTE=$(amixer get Master | grep -Po "\[off\]" | tail -1)

echo "Vol: $VOL | Mute: $MUTE"
