#!/usr/bin/env bash

~/.script/picom-toggle-awesome.sh

#==============
# System tools
#==============
# run /usr/lib/xfce-polkit/xfce-polkit
# run lxqt-policykit-agent
# run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg)
run lxsession

# run ibus-daemon -d -x
# run unclutter --root --timeout 3
# run xfce4-power-manager

#---------------
# Desktop Tools
#---------------
# $HOME/.bin/volume-osd &
# run flameshot
# run alttab -n 1
# run pamac-tray

#run blueman-tray
#run blueman-applet
# run nm-applet

# Sound Tray Icons
# restart start-pulseaudio-x11
# run pa-applet
# run pasystray


file=$HOME/.custom/autostart
if [ -f "$file" ]; then
    . "$file"
fi

# run xscreensaver

#cursor active at boot
# run xsetroot -cursor_name left_ptr -bg "#2a2a2a" -fg "#d6d6d6"
