#!/usr/bin/env zsh

. ~/.scripts/sounds
CUSTOM_FOLDER="$HOME/.custom"

# Aufbazu Array:
# Index 1: Custom Datei
# Index 2: Repository Datei
# Index 3: Ziel Datei
CUSTOMS=(
    "$CUSTOM_FOLDER/.gitconfig" "$HOME/.gitconfig-system"  "$HOME/.gitconfig"
    "$CUSTOM_FOLDER/bookmarks" "$HOME/.config/gtk-3.0/bookmarks.system"  "$HOME/.config/gtk-3.0/bookmarks"
)

ARRAY_SIZE=${#CUSTOMS[*]}
CUSTOM_COUNT=$(expr $ARRAY_SIZE / 3)

for (( i=1; i<=CUSTOM_COUNT; i++ ))
do
    CUSTOM_FILE=${CUSTOMS[($i-1)*3+1]}
    REPO_FILE=${CUSTOMS[($i-1)*3+2]}
    TARGET_FILE=${CUSTOMS[($i-1)*3+3]}
    echo "generate system file '$TARGET_FILE' from custom file '$CUSTOM_FILE'" 
    cp $REPO_FILE $TARGET_FILE
    tee $TARGET_FILE -a < $CUSTOM_FILE > /dev/null
    bat $TARGET_FILE --paging=never
done

