#!/usr/bin/env zsh

# sudo cryptsetup open /dev/sda1 WORKSPACE
sudo cryptsetup open /dev/disk/by-partlabel/WORKSPACE WORKSPACE --key-file=/crypto_keyfile.bin
sudo cryptsetup open /dev/disk/by-partlabel/BACKUP BACKUP --key-file=/crypto_keyfile.bin
sudo cryptsetup open /dev/disk/by-partlabel/BIGDATA BIGDATA --key-file=/crypto_keyfile.bin

sudo mount -t ext4 /dev/mapper/WORKSPACE /media/WORKSPACE
sudo mount -t ext4 /dev/mapper/BACKUP /media/BACKUP
sudo mount -t ext4 /dev/mapper/BIGDATA /media/BIGDATA
