#!/usr/bin/env bash
if pgrep -x "picom" >/dev/null; then
    notify-send "Picom disabled !"
    killall -q picom
    while pgrep -u $UID -x "picom" >/dev/null; do sleep 1; done
else
    notify-send "Picom loaded" "$PICOM_CONF"
    picom -b --dbus --config "$PICOM_CONF" &
fi
