#!/usr/bin/env zsh

# Snapshot erstellen
sudo timeshift --create
sudo update-grub

# System Update
$PACTOOL -Syyu --needed

# Flatpak Update
flatpak update -v --noninteractive

# Zinit Self update
. "$HOME/.zinit/bin/zinit.zsh"
zinit self-update

# Zinit Plugin update
zinit update --parallel
