code --install-extension aaghabeiki.gitdiffer
code --install-extension aaron-bond.better-comments
code --install-extension adam-watters.vscode-color-pick
code --install-extension adamvoss.vscode-languagetool
code --install-extension adamvoss.vscode-languagetool-de
code --install-extension adamvoss.vscode-languagetool-en
code --install-extension alefragnani.Bookmarks
code --install-extension alefragnani.project-manager
code --install-extension amandeepmittal.pug
code --install-extension angelomollame.conflict-squeezer
code --install-extension Angular.ng-template
code --install-extension be5invis.toml
code --install-extension bierner.emojisense
code --install-extension bodil.prettier-toml
code --install-extension ChakrounAnas.turbo-console-log
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension cyrilletuzi.angular-schematics
code --install-extension danielroedl.meld-diff
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension DavidWang.ini-for-vscode
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.git-extension-pack
code --install-extension donjayamanne.githistory
code --install-extension donjayamanne.jquerysnippets
code --install-extension dotdevru.dotdevru-metalua-formatter
code --install-extension DotJoshJohnson.xml
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension dunstontc.viml
code --install-extension dzannotti.vscode-babel-coloring
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension evan-buss.font-switcher
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension foxundermoon.shell-format
code --install-extension funkyremi.vscode-google-translate
code --install-extension ghaschel.vscode-angular-pug
code --install-extension Gruntfuggly.todo-tree
code --install-extension joelday.docthis
code --install-extension johnpapa.angular-essentials
code --install-extension johnpapa.Angular2
code --install-extension johnpapa.vscode-peacock
code --install-extension johnpapa.winteriscoming
code --install-extension jrebocho.vscode-random
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension mhutchie.git-graph
code --install-extension mikestead.dotenv
code --install-extension mrmlnc.vscode-autoprefixer
code --install-extension mrmlnc.vscode-pugbeautify
code --install-extension MS-CEINTL.vscode-language-pack-de
code --install-extension ms-python.python
code --install-extension ms-vscode.vs-keybindings
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension msjsdiag.debugger-for-edge
code --install-extension naumovs.color-highlight
code --install-extension PKief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension pranaygp.vscode-css-peek
code --install-extension Prisma.vscode-graphql
code --install-extension quicktype.quicktype
code --install-extension rokoroku.vscode-theme-darcula
code --install-extension royaction.color-manager
code --install-extension serayuzgur.crates
code --install-extension steoates.autoimport
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-german
code --install-extension sumneko.lua
code --install-extension syler.sass-indented
code --install-extension trixnz.vscode-lua
code --install-extension VimLeSai.front-end-ext-pack
code --install-extension vincaslt.highlight-matching-tag
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension waderyan.gitblame
code --install-extension wix.vscode-import-cost
code --install-extension Wscats.qf
code --install-extension wwm.better-align
code --install-extension yzhang.markdown-all-in-one
code --install-extension Zignd.html-css-class-completion
code --install-extension ziyasal.vscode-open-in-github
