code --install-extension aaron-bond.better-comments
code --install-extension adam-watters.vscode-color-pick
code --install-extension adamvoss.vscode-languagetool
code --install-extension adamvoss.vscode-languagetool-de
code --install-extension alefragnani.pascal
code --install-extension alefragnani.pascal-formatter
code --install-extension alexiv.vscode-angular2-files
code --install-extension amandeepmittal.pug
code --install-extension angelomollame.conflict-squeezer
code --install-extension antfu.i18n-ally
code --install-extension ardisaurus.gitflow-actions-sidebar
code --install-extension bierner.color-info
code --install-extension bmalehorn.vscode-fish
code --install-extension bpmn-io.vs-code-bpmn-io
code --install-extension christian-kohler.npm-intellisense
code --install-extension codezombiech.gitignore
code --install-extension coolbear.systemd-unit-file
code --install-extension coolchyni.beyond-debug
code --install-extension coolchyni.fpctoolkit
code --install-extension danielroedl.meld-diff
code --install-extension DavidWang.ini-for-vscode
code --install-extension deltaxml.xslt-xpath
code --install-extension donjayamanne.githistory
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension eliean.vscode-svn
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension formulahendry.code-runner
code --install-extension foxundermoon.shell-format
code --install-extension gccfeli.vscode-lua
code --install-extension ghaschel.vscode-angular-pug
code --install-extension girishakasapu.resxformatter
code --install-extension gurayyarar.dummytextgenerator
code --install-extension HookyQR.beautify
code --install-extension johnstoncode.svn-scm
code --install-extension keyring.Lua
code --install-extension lamartire.git-indicators
code --install-extension lunaryorn.fish-ide
code --install-extension mhutchie.git-graph
code --install-extension mrmlnc.vscode-pugbeautify
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-de
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.vs-keybindings
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension PrateekMahendrakar.resxpress
code --install-extension rogalmic.bash-debug
code --install-extension royaction.color-manager
code --install-extension skyapps.fish-vscode
code --install-extension spmeesseman.svn-scm-ext
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-german
code --install-extension sumneko.lua
code --install-extension traBpUkciP.vscode-npm-scripts
code --install-extension trixnz.vscode-lua
code --install-extension vscode-icons-team.vscode-icons
code --install-extension yinfei.luahelper
