#!/usr/bin/env bash

# shellcheck source=./config
source "./config"

sudo podman run \
    -dit \
    --restart unless-stopped \
    --privileged \
    --name $container_name \
    -p 9080:8080 \
    -v $data_dir/realm-config:/opt/keycloak/data/import \
    -d $image_name \
    start-dev

# Docker Prozesse prüfen
sudo podman ps -a
