#!/usr/bin/env bash

# shellcheck source=./config
source "./config"

# Ziel Ordner für volume vorbereiten
if [ -d "$data_dir" ]; then
    echo "datadir '$data_dir' exists, reuse it."
else
    echo "datadir '$data_dir' does not exists, create it!"
    sudo mkdir -p $data_dir/realm-config
fi
sudo chown -R root:root $data_dir
sudo chmod -R 'u=rwx,o=rwx,g=rwx' $data_dir
