#!/usr/bin/env zsh
. ~/.scripts/defs

# Init Install
initInstall "install_base"
sound count-down

###########################
# collect needed packages #
###########################

# system packages
install alacritty
install alttab-git
install arandr
install arj
install ark
install bashtop
install bat
install bitwarden
install bpytop
install clamav
install clamtk
install copyq
install dex
install docker
install docker-compose
install dpkg
install exa
install flameshot
install fzf
install fzf
install genius
install glances
install gnome-keyring
install gparted
install grc
install gtop
install hardinfo
install hstr
install htop
install i3lock-fancy
install ibus-daemon
install iftop
install iotop
install iptraf-ng
install kitty
install kteatime
install lhasa
install libgnome-keyring
install libsecret 
install multitail
install neofetch
install networkmanager
install networkmanager-openconnect
install nitrogen
install notify-send.sh
install numlockx
install openconnect
install p7zip
install packagekit
install picom-jonaburg-git
install pm-utils
install powershell-bin
install qbittorrent
install rsyslog
install s-tui
install shell-color-scripts
install spectacle
install stow
install time
install timeshift
install tldr++
install unclutter
install unrar
install watchexec
install xautolock
install xbindkeys
install xclip
install xdotool
install xorg-xbacklight
install xorg-xfd
install xorg-xsetroot
install xsel
install yad

# ArcoLinux Packages
if [ $IS_ARCO = true ]; then
	# Meta Packages
	install arcolinux-meta-log
	install arcolinux-meta-samba
	install arcolinux-meta-utilities
	# Interesting Packages
	install arcolinux-candy-beauty-git	
fi

if [ $IS_MANJARO = true ]; then
	install samba
	install manjaro-settings-samba
fi

# ssh 
install openssh
# TODO
# install lxqt-openssh-askpass
# install ssh-askpass-fullscreen

# Base Development Tools
install base-devel
install git
install gitflow-avh
install git-delta
install pass
install git-credential-manager-core-bin
install gradle
install jdk-openjdk
install jdk8-openjdk
install nodejs-emojione
install nodejs-lts-gallium
install nvm
install nuget
install npm
install svn
install yarn
install tk
install nsis

# awesome
install awesome-git

install xorg-server-xephyr
install luacheck
install awmtt

install eminent-git
install vicious
install lain-git
install shifty-git
install obvious-git

if [ $IS_ARCO = true ]; then
	install arcolinux-config-awesome-git
fi

# DotNet/Mono Setup
install dotnet-sdk
install mono
install mono-msbuild

# jetbrains apps
install jetbrains-toolbox

# config tools
install lxappearance

# utilities from gnome
install gnome-disk-utility
install gnome-system-monitor
install gnome-system-log
install gnome-logs
install gnome-calculator
install network-manager-applet

# polkits
install polkit
install polkit-qt5
install polkit-gnome
install xfce-polkit

install xscreensaver

install qt5ct
install qt5-styleplugins

# xfce developer
install xfce4-meta
install xfce4-power-manager

# file manager
# install mc
install ranger
install ufraw-thumbnailer

# Audio Radio
install radiotray-ng

# Nemo
install cinnamon-translations
install gtkhash-nemo
install nemo
install nemo-audio-tab
install nemo-compare
install nemo-emblems
install nemo-fileroller
install nemo-image-converter
install nemo-media-columns
install nemo-mediainfo-tab
install nemo-preview
install nemo-qml-plugin-notifications
install nemo-seahorse
install nemo-share

# Rofi Configs
if [ $IS_ARCO = true ]; then
	install arcolinux-rofi-git
	install arcolinux-rofi-themes-git
fi
install rofi
install rofimoji
install rofi-emoji

# File Indexing
install cerebro-git
install synapse
install synapse-admin-git
install fsearch
install recoll

# sound setup
install alsa-utils
install alsa-oss
install paprefs
install pasystray
install sp
install sound-theme-smooth
install gst123
install livecd-sounds
install mint-sounds
install tvolnoti
install ponymix
install pnmixer 

# Python libs
install python
install python-pip

# other
install bleachbit

# bluetooth setup
if [ $IS_MANJARO = true ]; then
	install manjaro-bluetooth
elif [ $IS_ENDEA = true ]; then
	install bluez 
	install bluez-utils 
	install pulseaudio-bluetooth
	install blueman
elif [ $IS_ARCO = true ]; then
	#install bluetooth-autoconnect
	install pulseaudio-bluetooth
	install blueman
	#install bluez
	#install bluez-hid2hci
	#install bluez-libs
	#install bluez-plugins
	#install bluez-tools
	#install bluez-utils

fi

# printer setup
if [ $IS_MANJARO = true ]; then
	install manjaro-printer
fi
install brother-mfc-j4420dw
install canon-cque
install cups-pdf
install hplip
install system-config-printer
install print-manager

install ghostscript 
install gsfonts 
install foomatic-db-engine 
install foomatic-db 
install foomatic-db-ppds 
install foomatic-db-nonfree 
install foomatic-db-nonfree-ppds 
install foomatic-db-gutenprint-ppds
install gutenprint 

# scanner setup
#install xsane
#install simple-scan
#install skanlite
#install colord-sane
#install sane

# Browser
install firefox-i18n-de
install chromium

# remmina
install remmina
install remmina-plugin-open
install remmina-plugin-rdesktop
install remmina-plugin-url
install remmina-plugin-folder
install remmina-plugin-open
install freerdp

# installation of important editors
install micro
install neovim
install visual-studio-code-bin
install typora-free

# utils for editors
install bash-completion
install clang
install fd
install gdb
install graphviz
install prettier
install ripgrep
install shellcheck
install tar

# wallpapers, themes, icons and fonts

# themes
if [ $IS_ARCO = true ]; then
	install arcolinux-arc-themes-git
fi
install materia-gtk-theme
install materia-theme
install adapta-maia-theme 
install maia-icon-theme 
install arc-maia-icon-theme

# icons
install arc-icon-theme
install paper-icon-theme
install papirus-icon-theme

# cursor
if [ $IS_ARCO = true ]; then
	install bibata-cursor-theme
else
	install bibata-cursor-theme-bin
fi
install bibata-cursor-translucent

# fonts
install font-manager

# powerline in linux console
install awesome-terminal-fonts
install terminus-font
install powerline-fonts

# install nerd-fonts-complete
# install nerd-fonts-fira-code
# install nerd-fonts-noto
# install noto-fonts-main
# install noto-fonts-emoji
# install nerd-fonts-roboto-mono
# install nerd-fonts-terminus
install ttf-meslo-nerd-font-powerlevel10k
install ttf-devicons
install ttf-jetbrains-mono
install ttf-proggy-clean
install ttf-twemoji
install ttf-twemoji-color
install ttf-weather-icons

# lightdm config
install lightdm
install lightdm-settings
install lightdm-gtk-greeter-settings
install lightdm-gtk-greeter
install lightdm-slick-greeter
install lightdm-webkit2-greeter
install lightdm-webkit2-theme-glorious
install lightdm-webkit2-clean
install lightdm-webkit2-theme-obsidian
install lightdm-webkit-theme-aether

if [ $IS_MANJARO = true ]; then
  install manjaro-slick-greeter-theme-light
fi

# grub
if [ $IS_MANJARO = false ]; then
	install grub-customizer
	install update-grub
fi

if [ $IS_MANJARO != true -a $IS_ARCO != true ]; then
	install grub2-theme-archlinux
fi

# btrfs tools
install grub-btrfs
install snapper
install snapper-rollback
install snapper-gui
install timeshift-autosnap

#########################
# collect optional apps #
#########################
#install epdfview

# gimicks
install cmatrix
install hollywood

# Office
install libreoffice-fresh
install libreoffice-fresh-de

# language files
install man-pages-de
install aspell-de
install mythes-de
install libmythes
install languagetool

# Browser
install google-chrome
install vivaldi
install microsoft-edge-dev-bin

# optional application packages
install aspell
install baobab
install gwenview
install partitionmanager
install playerctl
install teams

# graphics
# install imagemagick-full
# install libmagick-full
install inkscape
install gimp
install gimp-help-de
install pinta
install blender
install krita
install digikam

install glfw-x11
install phonon-qt5-vlc

# rust apps
install bat
install fd
install ripgrep
install tokei
install procs

###############################
# uninstall unneeded packages #
###############################
fullUninstall

#################################
# install all (needed) packages #
#################################
fullInstall

## FINISHING #
finish

# Fix Teams Black Screen
sudo ln -f -s /bin/true /usr/share/teams/resources/app.asar.unpacked/node_modules/slimcore/bin/rect-overlay
sudo ln -f -s /bin/true /usr/share/teams-insiders/resources/app.asar.unpacked/node_modules/slimcore/bin/rect-overlay

# micro plugins
micro -plugin install comment bounce editorconfig joinLines quoter filemanager bookmark \
	jump detectindent go snippets crystal quickfix wc manipulator \
	monokai-dark gotham-colors nordcolors 

sound complete
