#!/usr/bin/env bash

. "$HOME/.scripts/defs"

install ansible
ansible-galaxy collection install -r .ansible/lib/requirements.yml

# Init Install
initInstall "install_ansible"

# Config pacman
if [ -f /etc/pacman.conf ]; then
	sudo sed -i 's/^#Color$/Color/g' /etc/pacman.conf
	sudo sed -i 's/^.*ParallelDownloads.*$/ParallelDownloads = 10/g' /etc/pacman.conf
	sudo sed -i 's/^.*VerbosePkgLists.*$/VerbosePkgLists/g' /etc/pacman.conf
	errorCheck "pacman config"
fi

# Config pamac
if [ -f /etc/pamac.conf ]; then
	sudo sed -i 's/^.*ILoveCandy$/ILoveCandy/g' /etc/pamac.conf
	sudo sed -i 's/^.*EnableAUR$/EnableAUR/g' /etc/pamac.conf
	sudo sed -i 's/^.*KeepBuiltPkgs$/KeepBuiltPkgs/g' /etc/pamac.conf
	errorCheck "pamac config"
fi

# disable sudo password
echo "Cmnd_Alias INSTALL = /usr/bin/pacman, /usr/share/pacman
Cmnd_Alias POWER = /usr/bin/pm-hibernate, /usr/bin/pm-powersave, /usr/bin/pm-suspend-hybrid, /usr/bin/pm-suspend
Defaults timestamp_timeout=300
$USER ALL=(ALL) NOPASSWD:INSTALL,POWER
$USER ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/100-myrules

sudo chmod -R -v +x ~/.scripts
sudo chmod -R -v +x ~/.bin
errorCheck "set script flags"

if [ $IS_FEDORA_BASED = true ]; then
	sudo wget -O /usr/bin/awmtt https://raw.githubusercontent.com/mikar/awmtt/master/awmtt.sh
	sudo chmod a+x /usr/bin/awmtt
fi

## FINISHING #
finish

# if [ $IS_ARCH_BASED = true ]; then
# 	sudo pamac build --no-confirm qt5-styleplugins
# fi
