#!/usr/bin/env bash

. "$HOME/.scripts/defs"

csource "$HOME/.profile"

sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm -y
sudo dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y

ansible-playbook ~/.ansible/lib/nvidia-install.yml --flush-cache
errorCheck "run ansible playbook"
