#!/usr/bin/env zsh

sudo pacman -Syy --needed lsb-release

. ~/.scripts/defs

if [ $IS_MANJARO = true ]; then
	sudo pacman -S --needed yay
	yay -S --needed paru-bin
fi

# Init Install
initInstall "install_init"
sound count-down &

# Config pacman
if [ -f /etc/pacman.conf ]; then
	sudo sed -i 's/^#Color$/Color/g' /etc/pacman.conf
	sudo sed -i 's/^.*ParallelDownloads.*$/ParallelDownloads = 10/g' /etc/pacman.conf
	sudo sed -i 's/^.*VerbosePkgLists.*$/VerbosePkgLists/g' /etc/pacman.conf
	errorCheck "pacman config"
fi

# Config pamac
if [ -f /etc/pamac.conf ]; then
	sudo sed -i 's/^.*ILoveCandy$/ILoveCandy/g' /etc/pamac.conf
	sudo sed -i 's/^.*EnableAUR$/EnableAUR/g' /etc/pamac.conf
	sudo sed -i 's/^.*KeepBuiltPkgs$/KeepBuiltPkgs/g' /etc/pamac.conf
	errorCheck "pamac config"
fi

eval "sudo pacman -S --needed $PACKER_ALL git base-devel curl colorgcc go ruby rust"
errorCheck "installation base-devel"

# disable sudo password
echo "Cmnd_Alias INSTALL = /usr/bin/pacman, /usr/share/pacman
Cmnd_Alias POWER = /usr/bin/pm-hibernate, /usr/bin/pm-powersave, /usr/bin/pm-suspend-hybrid, /usr/bin/pm-suspend
Defaults timestamp_timeout=300
$USER ALL=(ALL) NOPASSWD:INSTALL,POWER
$USER ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/100-myrules

sudo chmod -R -v +x ~/.scripts
sudo chmod -R -v +x ~/.bin
errorCheck "set script flags"

# base install tools
install archey4
install exa
install kitty
install lsd
install micro
install polkit
install ranger
install python2-bin

# base install awesome 
if [ $IS_MANJARO = true ]; then
    install manjaro-awesome-settings
fi
if [ $IS_ARCO = true ]; then
    install arcolinux-config-awesome-git
fi

# awesome
install awesome-git
install awmtt
install picom
install lain-git
install rofi
install xfce4-meta

###############################
# uninstall unneeded packages #
###############################
fullUninstall

#################################
# install all (needed) packages #
#################################
fullInstall

## FINISHING #
finish

sound complete
