#!/usr/bin/env zsh

. ~/.scripts/defs

# Init Install
initInstall "install_dev"

###########################################
# collect for development needed packages #
###########################################

# Base Development Tools

if [ $IS_ARCH_BASED = true ]; then
	install base-devel
	install gitflow-avh
	install gradle
	install jdk-openjdk
	install jdk17-openjdk
	install svn
	install nsis

	# DotNet/Mono Setup
	install dotnet-sdk
	install mono
	install mono-msbuild
	install pass
	install nsis
	install shellcheck
fi

if [ $IS_FEDORA_BASED = true ]; then
	sudo dnf copr enable elegos/gitflow -y
	
	install subversion
	install mingw32-nsis
	
	# DotNet/Mono Setup
	install mono-complete
	install gitflow
	install dotnet-sdk-6.0
	install dotnet-sdk-7.0
fi

# nvm
curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
nvm install 18
corepack enable	

install nuget
sudo cargo install git-delta ripgrep --root /usr

install cmake	
install cargo
install rust
install git
install npm
install svn
install tk
install jq
install python-pip

# utils for editors
install bash-completion
install clang
install gdb

###############################
# uninstall unneeded packages #
###############################
fullUninstall

#################################
# install all (needed) packages #
#################################
fullInstall

## FINISHING #
finish
