#!/usr/bin/env zsh
. ~/.scripts/defs

# Init Install
initInstall "install_vm"
sound count-down

#####################
# init distro check #
#####################

INSTALL_VIRTIO=true
INSTALL_VIRTUALBOX=false

###########################
# collect needed packages #
###########################

# virtualbox
if [ $INSTALL_VIRTUALBOX = true ]; then
	if [ $IS_MANJARO = true ]; then
		install virtualbox
		install virtualbox-ext-oracle
	else
		install virtualbox
		install virtualbox-ext-oracle
		install virtualbox-host-modules-arch
		install linux-headers
	fi
fi

# libvirt service and manager
if [ $INSTALL_VIRTIO = true ]; then
	install virt-manager
	install virtio-win
	install qemu
	install qemu-arch-extra
	install libvirt
	install iptables-nft
	install ebtables
	install dnsmasq
	install vde2 
	install bridge-utils 
	install openbsd-netcat 
	install ovmf
fi

###############################
# uninstall unneeded packages #
###############################
fullUninstall

#################################
# install all (needed) packages #
#################################
fullInstall

## FINISHING #
finish

sudo systemctl enable --now libvirtd
errorCheck "libvirtd service"

sound complete
