#!/usr/bin/env bash

source "$HOME/.scripts/defs"

# Init Install
initInstall "install_arduino"
sound count-down

###########################
# collect needed packages #
###########################

# arduino and other microcontroler development

# IDEs
install arduino

# Microcontroler Develop
install platformio
install esptool

# cnc tools
install inkscape
install blender
# install lux
# install luxcorerender-bin

# utils for editors
install clang
install gdb
install graphviz
install prettier
install shellcheck

###############################
# uninstall unneeded packages #
###############################
fullUninstall

#################################
# install all (needed) packages #
#################################
fullInstall

yarn global add cncjs

pip install wheel
pip install esphome

sudo usermod -a -G "$(stat -c "%G" /dev/ttyUSB0)" $USER

## FINISHING #
finish

sound complete
