#!/usr/bin/env zsh

. ~/.scripts/defs

# Init Install
initInstall "install_base"
sound count-down

###########################
# collect needed packages #
###########################

# Manjaro Packages
if [ $IS_MANJARO = true ]; then
    install manjaro-awesome-settings
    install samba
    install manjaro-settings-samba
fi

# ArcoLinux Packages
if [ $IS_ARCO = true ]; then
    install arcolinux-config-awesome-git
    # Meta Packages
    install arcolinux-meta-log
    install arcolinux-meta-logout
    install arcolinux-meta-fun
    install arcolinux-meta-samba
    install arcolinux-meta-utilities
    # Interesting Packages
    install arcolinux-candy-beauty-git
fi

# awesome
install awesome-git
install lain-git
install awmtt

# system packages
install acpi
install acpid
install alttab-git
install arandr
install archey4
install archivefs
install arj
install ark
install bashtop
install bat
install bitwarden
install blueman
install bpytop
install brightnessctl
install clamav
install clamtk
install copyq
install dex
install dnsutils
install docker
install docker-compose
install dpkg
install exa
install feh
install ffmpeg
install flameshot
install fzf
install genius
install glances
install glogg
install gnome-keyring
install gparted
install gpick
install grc
install gtop
install hardinfo
install hstr
install htop
install ibus-daemon
install iftop
install inotify-tools
install iotop
install iptraf-ng
install jq
install kitty
install kteatime
install lhasa
install libgnome-keyring
install libsecret
install light
install lscolors-git
install lsd
install luacheck
install micro
install mpc
install mpd
install mpdris2
install mpv
install multitail
install ncmpcpp
install networkmanager
install networkmanager-openconnect
install nitrogen
install notify-send.sh
install numlockx
install openconnect
install p7zip
install packagekit
install picom
install playerctl
install pm-utils
install polkit-gnome
install powershell-bin
install python-mutagen
install qjournalctl
install qbittorrent
install ranger
install redshift
install ripgrep
install rsyslog
install s-tui
install scrot
install shell-color-scripts
install spectacle
install stow
install time
install timeshift
install toilet
install toilet-fonts
install unclutter
install unrar
install upower
install watchexec
install wezterm
install wmctrl
install xautolock
install xbindkeys
install xclip
install xclip
install xdotool
install xdotool
install xfce4-power-manager
install xorg-server-xephyr
install xorg-xbacklight
install xorg-xfd
install xorg-xsetroot
install xscreensaver
install xsel

# polkits
install polkit-gnome
install polkit
install polkit-qt5

# sound setup
install alsa-oss
install alsa-utils
install gst123
install livecd-sounds
install pamixer
install paprefs
install pasystray
install pavucontrol
install pnmixer
install ponymix
install sound-theme-smooth
install sp
install tvolnoti
install pulseeffects-legacy

if [ $IS_ARCO = true ]; then
    install pa-applet-git
fi

if [ $IS_MANJARO = false ]; then
    install pulseaudio-alsa
    install pulseaudio-bluetooth
    install pulseaudio-equalizer
fi

# ssh
install openssh

# Base Development Tools
install base-devel
install git
install gitflow-avh
install git-delta
install pass
install gradle
install jdk-openjdk
install jdk8-openjdk
install nodejs-emojione
uninstall nodejs-lts-gallium
install nodejs
install nvm
install nuget
install npm
install svn
install yarn
install tk
install nsis
install jq

# DotNet/Mono Setup
install dotnet-sdk
install mono
install mono-msbuild

# config tools
install lxappearance

# utilities from gnome
install gnome-disk-utility
install gnome-system-monitor
install gnome-system-tools
install gnome-logs
install gnome-calculator
install network-manager-applet

install qt5ct
install qt5-styleplugins


# file manager
install mc
install rnr-fm
install ranger
install ranger_devicons-git
install ufraw-thumbnailer

# Nemo
install cinnamon-translations
install gtkhash-nemo
install nemo
install nemo-audio-tab
install nemo-compare
install nemo-emblems
install nemo-fileroller
install nemo-image-converter
install nemo-media-columns
install nemo-mediainfo-tab
install nemo-preview
install nemo-qml-plugin-notifications
install nemo-seahorse
install nemo-share

# Rofi Configs
if [ $IS_ARCO = true ]; then
    install arcolinux-rofi-git
    install arcolinux-rofi-themes-git
fi
install rofi
install rofimoji
install rofi-emoji

# Python libs
install python
install python-pip

# other
install bleachbit

# bluetooth setup
if [ $IS_MANJARO = true ]; then
    install manjaro-bluetooth
fi

if [ $IS_ARCO = true ]; then
    #install bluetooth-autoconnect
    install blueman
    #install bluez
    #install bluez-hid2hci
    #install bluez-libs
    #install bluez-plugins
    #install bluez-tools
    #install bluez-utils
fi

# printer setup
if [ $IS_MANJARO = true ]; then
    install manjaro-printer
fi
install brother-mfc-j4420dw
install canon-cque
install cups-pdf
install hplip
install system-config-printer
install print-manager

install ghostscript
install gsfonts
install foomatic-db-engine
install foomatic-db
install foomatic-db-ppds
install foomatic-db-nonfree
install foomatic-db-nonfree-ppds
install foomatic-db-gutenprint-ppds
install gutenprint

# installation of important editors
install micro
install neovim
install visual-studio-code-bin

# utils for editors
install bash-completion
install clang
install fd
install gdb
install graphviz
install prettier
install ripgrep
install shellcheck
install tar

# wallpapers, themes, icons and fonts

# themes
# install themix-full-git
# install themix-plugin-base16-git

if [ $IS_ARCO = true ]; then
    # install arcolinux-arc-aqua-git
    install arcolinux-arc-archlinux-blue-git
    install arcolinux-arc-arcolinux-blue-git
    # install arcolinux-arc-azul-git
    # install arcolinux-arc-azure-dodger-blue-git
    # install arcolinux-arc-blood-git
    # install arcolinux-arc-blue-sky-git
    # install arcolinux-arc-botticelli-git
    # install arcolinux-arc-bright-lilac-git
    # install arcolinux-arc-bright-lime-green-git
    # install arcolinux-arc-carnation-git
    # install arcolinux-arc-carolina-blue-git
    # install arcolinux-arc-casablanca-git
    # install arcolinux-arc-crimson-git
    # install arcolinux-arc-dawn-git
    # install arcolinux-arc-dracul-git
    # install arcolinux-arc-emerald-git
    # install arcolinux-arc-evopop-git
    # install arcolinux-arc-fern-git
    # install arcolinux-arc-fire-git
    # install arcolinux-arc-froly-git
    # install arcolinux-arc-havelock-git
    # install arcolinux-arc-hibiscus-git
    # install arcolinux-arc-light-blue-grey-git
    # install arcolinux-arc-light-blue-surfn-git
    # install arcolinux-arc-light-salmon-git
    # install arcolinux-arc-mandy-git
    # install arcolinux-arc-mantis-git
    # install arcolinux-arc-medium-blue-git
    # install arcolinux-arc-niagara-git
    # install arcolinux-arc-nice-blue-git
    # install arcolinux-arc-numix-git
    # install arcolinux-arc-orchid-git
    # install arcolinux-arc-pale-grey-git
    # install arcolinux-arc-paper-git
    # install arcolinux-arc-pink-git
    # install arcolinux-arc-polo-git
    # install arcolinux-arc-punch-git
    # install arcolinux-arc-red-orange-git
    # install arcolinux-arc-rusty-orange-git
    # install arcolinux-arc-sky-blue-git
    # install arcolinux-arc-slate-grey-git
    install arcolinux-arc-smoke-git
    install arcolinux-arc-soft-blue-git
    # install arcolinux-arc-tacao-git
    # install arcolinux-arc-tangerine-git
    # install arcolinux-arc-tory-git
    # install arcolinux-arc-vampire-git
    # install arcolinux-arc-warm-pink-git
fi

if [ $IS_MANJARO = true ]; then
    install kvantum-manjaro
    install maia-console
    install maia-wallpaper
    install papirus-maia-icon-theme
    install xcursor-maia    
    install manjaro-artwork
    install manjaro-artwork-extra
fi


# icons
if [ $IS_MANJARO = true ]; then
    install manjaro-artwork-icons
    install papirus-maia-icon-theme
    install maia-icon-theme
fi

if [ $IS_ARCO = true ]; then
    install surfn-icons-git
    install paper-icon-theme
    install papirus-icon-theme
    # install tela-icon-theme
    
    # install sardi-colora-variations-icons-git
    # install sardi-flat-colora-variations-icons-git
    # install sardi-flat-mint-y-icons-git
    # install sardi-flat-mixing-icons-git
    install sardi-flexible-colora-variations-icons-git
    install sardi-flexible-luv-colora-variations-icons-git
    install sardi-flexible-mint-y-icons-git
    install sardi-flexible-mixing-icons-git
    install sardi-flexible-variations-icons-git
    # install sardi-ghost-flexible-colora-variations-icons-git
    # install sardi-ghost-flexible-mint-y-icons-git
    # install sardi-ghost-flexible-mixing-icons-git
    # install sardi-ghost-flexible-variations-icons-git
    # install sardi-icons
    # install sardi-mint-y-icons-git
    # install sardi-mixing-icons-git
    # install sardi-mono-colora-variations-icons-git
    # install sardi-mono-mint-y-icons-git
    # install sardi-mono-mixing-icons-git
    # install sardi-mono-numix-colora-variations-icons-git
    # install sardi-mono-papirus-colora-variations-icons-git
    # install sardi-orb-colora-mint-y-icons-git
    # install sardi-orb-colora-mixing-icons-git
    # install sardi-orb-colora-variations-icons-git
fi

# Extra
if [ $IS_ARCO = true ]; then
    # install arcolinux-candy-beauty-git
    # install edu-candy-beauty-tela-git
    # install edu-candy-beauty-arc-git
    # install edu-papirus-dark-tela-git
    # install edu-candy-beauty-arc-mint-red-git
    # install edu-papirus-dark-tela-grey-git
    # install edu-candy-beauty-arc-mint-grey-git
    # install edu-vimix-dark-tela-git
    install edu-system-git
    install edu-skel-git
fi

# cursor
if [ $IS_MANJARO = true ]; then
    install maia-cursor-theme
fi
if [ $IS_ARCO = true ]; then
    install bibata-cursor-theme
    install bibata-cursor-translucent
fi

# fonts
install font-manager

# powerline in linux console
install awesome-terminal-fonts
install powerline-fonts
install powerline-console-fonts-git
install terminus-font
install ttf-meslo-nerd-font-powerlevel10k
install zsh-theme-powerlevel10k

# install nerd-fonts-complete
install nerd-fonts-fira-code
install nerd-fonts-noto
install nerd-fonts-source-code-pro
install nerd-fonts-terminus
install ttf-cascadia-code
install ttf-devicons
install ttf-fira-code
install ttf-iosevka
install ttf-jetbrains-mono
install ttf-meslo-nerd-font-powerlevel10k
install ttf-nerd-fonts-symbols
install ttf-twemoji
install ttf-weather-icons

# lightdm config
install lightdm
install lightdm-settings
install lightdm-gtk-greeter-settings
install lightdm-gtk-greeter
install lightdm-slick-greeter

# grub
if [ $IS_MANJARO = false ]; then
    install grub-customizer
    install update-grub
fi

if [ $IS_MANJARO != true -a $IS_ARCO != true ]; then
    install grub2-theme-archlinux
fi

# btrfs tools
install grub-btrfs

#########################
# collect optional apps #
#########################
#install epdfview

# language files
install man-pages-de
install aspell-de
install mythes-de
install libmythes
install languagetool

# Browser
install vivaldi

# rust apps
install bat
install fd
install ripgrep
install tokei
install procs

###############################
# uninstall unneeded packages #
###############################
fullUninstall

#################################
# install all (needed) packages #
#################################
fullInstall

## FINISHING #
finish

# ranger plugins
mkdir "$HOME/.config/ranger/plugins"
ln -sf /usr/share/ranger/plugins/ranger_devicons ~/.config/ranger/plugins/ranger_devicons

# twitter emoji font
sudo ln -sf /usr/share/fontconfig/conf.avail/75-twemoji.conf /etc/fonts/conf.d/75-twemoji.conf

# micro plugins
micro -plugin install comment editorconfig joinLines quoter filemanager \
jump detectindent go snippets crystal quickfix wc manipulator \
diff ftoptions linter literate status \
monokai-dark gotham-colors nordcolors
micro -plugin update

# rebuilds
sudo pamac build --no-confirm qt5-styleplugins

sound complete
