#!/usr/bin/env bash

source "$HOME/.scripts/defs"

# config slick-greeter
GREETER_THEME="$MAIN_THEME"
GREETER_ICON="$ICON_THEME"
GREETER_CURSOR="$CURSOR_THEME"

if [ $IS_MANJARO = true ]; then
    GREETER_BACKGROUND="/usr/share/backgrounds/manjaro-wallpapers-18.0/manjaro-cat.jpg"
    elif [ $IS_ARCO = true ]; then
    GREETER_BACKGROUND="/usr/share/backgrounds/arcolinux/arco-login.jpg"
else
    GREETER_BACKGROUND="/usr/share/backgrounds/desert.png"
fi

if [ $IS_ARCO = true ]; then
    sudo convert /usr/share/backgrounds/archlinux-login-backgrounds/background15.jpg /usr/share/grub/themes/Vimix/background.png
    errorCheck "convert arcolinux grub image"
    sudo sed -i 's/.*GRUB_THEME=.*$/GRUB_THEME="\/usr\/share\/grub\/themes\/Vimix\/theme.txt"/g' /etc/default/grub
    errorCheck "move arcolinux grub file"
fi

sound complete
