#!/usr/bin/env bash

source "$HOME/.scripts/defs"

source "$HOME/.profile"

if [ "$IS_RHEL" = true ]; then
	install ansible-core
fi

if [ "$IS_FEDORA" = true ]; then
	sudo dnf install -y ansible redhat-lsb-core dnf-plugins-core
fi

if [ "$IS_ARCH_BASED" = true ]; then
	sudo pacman -Syy ansible lsb-release
fi

if [ "$IS_DEBIAN_BASED" = true ]; then
	sudo apt install -y ansible
fi

errorCheck "install ansible"

ansible-galaxy collection install -r ~/.ansible/lib/collections.yml
errorCheck "install ansible-galaxy collections"

ansible-galaxy role install -r ~/.ansible/lib/roles.yml
errorCheck "install ansible-galaxy roles"

ansible-playbook ~/.ansible/sudo.yml --flush-cache
errorCheck "set sudoer rights"

ansible-playbook ~/.ansible/system.yml
errorCheck "run ansible playbook"

