#!/usr/bin/env bash

source "$HOME/.scripts/defs"

# Init Install
initInstall "install_apps"
sound count-down

#########################
# collect optional apps #
#########################

# graphics
# install imagemagick-full
# install libmagick-full
install inkscape
install gimp
install gimp-help-de
install pinta
install blender
install krita
# install digikam
install feh
install imv

# optional application packages
install aspell
install baobab-gtk3
install kdeconnect

# install gwenview
install partitionmanager
install playerctl
install teams
install teams-for-linux

# Browser
install firefox-i18n-de
install chromium
install google-chrome
install microsoft-edge-dev-bin

# gimicks
if [ $IS_ARCO = true ]; then
	install cmatrix-git
else
	install cmatrix
	install hollywood
fi

# Office
install libreoffice-fresh
install libreoffice-fresh-de

# remmina
install remmina
install remmina-plugin-open
install remmina-plugin-rdesktop
install remmina-plugin-url
install remmina-plugin-folder
install remmina-plugin-open
install freerdp

# scanner setup
#install xsane
#install simple-scan
#install skanlite
#install colord-sane
#install sane

# File Indexing
install fsearch

# jetbrains apps
install jetbrains-toolbox

###############################
# uninstall unneeded packages #
###############################
fullUninstall

#################################
# install all (needed) packages #
#################################
fullInstall

## FINISHING #
finish

# Fix Teams Black Screen
sudo ln -f -s /bin/true /usr/share/teams/resources/app.asar.unpacked/node_modules/slimcore/bin/rect-overlay

# flatpaks
flatpak install shortwave
# flatpak install bottles

sudo flatpak override --env=GTK_THEME=Adwaita:dark
gsettings set org.gnome.desktop.interface color-scheme prefer-dark
