#!/usr/bin/env bash

source "$HOME/.scripts/defs"

# Init Install
initInstall "install_games"
sound count-down

##########################
# collect optional games #
##########################

# graphics
# install imagemagick-full
# install libmagick-full
install wesnoth
install 0ad
install widelands
install runescape

###############################
# uninstall unneeded packages #
###############################
fullUninstall

#################################
# install all (needed) packages #
#################################
fullInstall

## FINISHING #
finish
