---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by stira.
--- DateTime: 13.05.20 09:46
---

-- Standard awesome library
local gears = require("gears")
local awful = require("awful")

gdebug = require("gears.debug")

local xresources = require("beautiful.xresources")
local dpi = xresources.apply_dpi

local utils = require("utils")

-- Theme handling library
local beautiful = require("beautiful")

local colors = utils.get_current_theme()

local themes = {
  "multicolor", -- 1
  "powerarrow", -- 2
  "powerarrow-blue", -- 3
  "blackburn" -- 4
}

-- choose your theme here
local chosen_theme = themes[3]

local theme_path = string.format("%s/.config/awesome/themes/%s/theme.lua", os.getenv("HOME"), chosen_theme)
beautiful.init(theme_path)

-- {{{ Variable definitions
-- Themes define colours, icons, font and wallpapers.

themename = "gtk" -- theme name
themetype = "dark"
terminal = "alacritty" -- default terminal
editor = "code" -- default editor
editor_cmd = editor

-- extern apps definition
browser = "firefox"
clipboard = "copyq"
composite = "picom"
filemanager = "krusader"
filemanager_root = "kdesu krusader"
guard = "gnome-system-monitor"
mail = "thunderbird"
screenlook = "blurlock"
tasks = "xfce4-taskmanager"

-- themes
themepath = gears.filesystem.get_xdg_config_home() .. "awesome/"
themefile = themepath .. "/theme.lua"

-- tag definitions
tag_Develop = " Develop"
tag_DevConsole = " Develop Consolen"
tag_Git = " Git"
tag_Divers = " Sonstiges"
tag_Files = " Dateien"
tag_Teams = " Teams"
tag_VM = " VirtualBox"
tag_Web = " Web"
tag_Media = " Audio /  Video"
tag_Admin = " Admin"
tag_Status = " Status"

-- Default modkey.
-- Usually, Mod4 is the key with a logo between Control and Alt.
-- If you do not like this or do not have such a key,
-- I suggest you to remap Mod4 to another key using xmodmap or other tools.
-- However, you can use another modifier like Mod1, but it may interact with others.
modkey = "Mod4"

-- Table of layouts to cover with awful.layout.inc, order matters.
awful.layout.layouts = {
  awful.layout.suit.floating,
  awful.layout.suit.tile,
  -- TODO implment layout editor, see: https://github.com/xinhaoyuan/layout-machi
  --machi.default_layout,
  awful.layout.suit.tile.left,
  awful.layout.suit.tile.bottom,
  awful.layout.suit.tile.top,
  awful.layout.suit.fair,
  awful.layout.suit.fair.horizontal,
  awful.layout.suit.spiral,
  awful.layout.suit.spiral.dwindle,
  awful.layout.suit.max,
  awful.layout.suit.max.fullscreen,
  awful.layout.suit.magnifier,
  awful.layout.suit.corner.nw,
  awful.layout.suit.corner.ne,
  awful.layout.suit.corner.sw,
  awful.layout.suit.corner.se
}
-- }}}
