---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by stira.
--- DateTime: 13.05.20 09:46
---

-- Standard awesome library
local gears          = require("gears")
local awful          = require("awful")

gdebug               = require("gears.debug")

local xresources     = require("beautiful.xresources")
local dpi            = xresources.apply_dpi

local utils          = require("utils")

local colors         = utils.get_current_theme()

local machi          = require("layout-machi")
require("beautiful").layout_machi = machi.get_icon()

-- {{{ Variable definitions
-- Themes define colours, icons, font and wallpapers.

themename            = "default" -- theme name
themetype            = "dark"
terminal             = "alacritty" -- default terminal
editor               = "kate" -- default editor
editor_cmd           = editor

-- extern apps definition
browser              = "firefox"
clipboard            = "copyq"
composite            = "picom"
filemanager          = "krusader"
filemanager_root     = "kdesu krusader"
guard                = "gnome-system-monitor"
mail                 = "thunderbird"
screenlook           = "blurlock"
tasks                = "xfce4-taskmanager"

-- themes
themepath            = gears.filesystem.get_xdg_config_home() .. "awesome/themes/"
themefile            = themepath .. themename .. "/theme.lua"

my_bg_normal         = colors.background
my_bg_focus          = colors.focused_background
my_bg_urgent         = colors.color1
my_bg_minimize       = colors.inactive_background
my_bg_systray        = my_bg_normal

my_fg_normal         = colors.foreground
my_fg_focus          = colors.focused_foreground
my_fg_urgent         = colors.color15
my_fg_minimize       = colors.inactive_foreground

my_useless_gap       = dpi(3)
my_border_width      = dpi(1)

my_border_normal     = my_fg_normal
my_border_focus      = my_fg_focus
my_border_marked     = "#00FF00"

-- tag definitions
tag_Develop          = " Develop"
tag_DevConsole       = " Develop Consolen"
tag_Divers           = " Sonstiges"
tag_Teams            = " Teams"
tag_VM               = " VirtualBox"
tag_Web              = " Web"
tag_Media            = " Audio /  Video"
tag_Admin            = " Admin"
tag_Status           = " Status"

-- Default modkey.
-- Usually, Mod4 is the key with a logo between Control and Alt.
-- If you do not like this or do not have such a key,
-- I suggest you to remap Mod4 to another key using xmodmap or other tools.
-- However, you can use another modifier like Mod1, but it may interact with others.
modkey               = "Mod4"

-- Table of layouts to cover with awful.layout.inc, order matters.
awful.layout.layouts = {
  awful.layout.suit.floating,
  awful.layout.suit.tile,
  -- TODO implment layout editor, see: https://github.com/xinhaoyuan/layout-machi
  --machi.default_layout,
  awful.layout.suit.tile.left,
  awful.layout.suit.tile.bottom,
  awful.layout.suit.tile.top,
  awful.layout.suit.fair,
  awful.layout.suit.fair.horizontal,
  awful.layout.suit.spiral,
  awful.layout.suit.spiral.dwindle,
  awful.layout.suit.max,
  awful.layout.suit.max.fullscreen,
  awful.layout.suit.magnifier,
  awful.layout.suit.corner.nw,
  awful.layout.suit.corner.ne,
  awful.layout.suit.corner.sw,
  awful.layout.suit.corner.se,
}
-- }}}
