---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by stira.
--- DateTime: 13.05.20 09:46
---

-- Standard awesome library
gears = require("gears")
awful = require("awful")

gdebug = require("gears.debug")

xresources = require("beautiful.xresources")
dpi = xresources.apply_dpi

utils = require("utils")

-- Theme handling library
beautiful = require("beautiful")

local colors = utils.get_current_theme()

local themes = {
    "multicolor", -- 1
    "powerarrow", -- 2
    "powerarrow-blue", -- 3
    "blackburn", -- 4
    "mytheme" -- 5
}

-- choose your theme here
chosen_theme = themes[1]

theme_path = string.format("%s/.config/awesome/themes/%s/theme.lua", os.getenv("HOME"), chosen_theme)
beautiful.init(theme_path)

-- {{{ Variable definitions
-- Themes define colours, icons, font and wallpapers.

themename = "gtk" -- theme name
themetype = "dark"

-- modkey or mod4 = super key
modkey = "Mod4"
altkey = "Mod1"
controlkey = "Control"
shiftkey = "Shift"
returnkey = "Return"
escapekey = "Escape"

-- personal variables
-- change these variables if you want
browser1 = "firefox"
browser2 = "firefox"
browser3 = "firefox"
editor = os.getenv("EDITOR") or "nano"
editorgui = "Geany"
filemanager = "pcmanfm"
mailclient = "evolution"
mediaplayer = "spotify"
terminal = "termite"
virtualmachine = "virtualbox"

-- key groups
kgApplication = "application"
kgAwesome = "awesome"
kgClient = "client"
kgLayout = "layout"
kgMaster = "master"
kgMenu = "menu"
kgScreen = "screen"
kgSound = "sound"
kgSystem = "system"
kgTag = "tag"

-- tag definitions
tag_Develop = " Develop"
tag_DevConsole = " Develop Consolen"
tag_Git = " Git"
tag_Divers = " Sonstiges"
tag_Files = " Dateien"
tag_Teams = " Teams"
tag_VM = " VirtualBox"
tag_Web = " Web"
tag_Media = " Audio /  Video"
tag_Admin = " Admin"
tag_Status = " Status"

-- Default modkey.
-- Usually, Mod4 is the key with a logo between Control and Alt.
-- If you do not like this or do not have such a key,
-- I suggest you to remap Mod4 to another key using xmodmap or other tools.
-- However, you can use another modifier like Mod1, but it may interact with others.
modkey = "Mod4"

-- Table of layouts to cover with awful.layout.inc, order matters.
awful.layout.layouts = {
  awful.layout.suit.floating,
  awful.layout.suit.tile,
  -- TODO implment layout editor, see: https://github.com/xinhaoyuan/layout-machi
  --machi.default_layout,
  awful.layout.suit.tile.left,
  awful.layout.suit.tile.bottom,
  awful.layout.suit.tile.top,
  awful.layout.suit.fair,
  awful.layout.suit.fair.horizontal,
  awful.layout.suit.spiral,
  awful.layout.suit.spiral.dwindle,
  awful.layout.suit.max,
  awful.layout.suit.max.fullscreen,
  awful.layout.suit.magnifier,
  awful.layout.suit.corner.nw,
  awful.layout.suit.corner.ne,
  awful.layout.suit.corner.sw,
  awful.layout.suit.corner.se
}
-- }}}
