---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by stira.
--- DateTime: 13.05.20 11:08
---

-- Standard Definitions
require("definitions")

-- Standard awesome library
local awful       = require("awful")

-- Theme handling library
local beautiful   = require("beautiful")

-- {{{ Rules
-- Rules to apply to new clients (through the "manage" signal).
awful.rules.rules = {

  -- All clients will match this rule.
  {
    rule       = {},
    properties = {
      border_width     = beautiful.border_width,
      border_color     = beautiful.border_normal,
      focus            = awful.client.focus.filter,
      raise            = true,
      keys             = clientkeys,
      buttons          = clientbuttons,
      screen           = awful.screen.preferred,
      placement        = awful.placement.no_overlap + awful.placement.no_offscreen,
      size_hints_honor = true,
      --opacity          = 1
    }
  },

  -- Floating clients.
  {
    rule_any   = {
      instance = {
        "copyq",
      },
      class    = {
        "GParted",
        "Grub Customizer",
        "JetBrains Toolbox",
        "Lightdm-gtk-greeter-settings",
        "Lightdm-settings",
        "Lxappearance",
        "Manjaro Settings Manager",
        "Nitrogen",
        "Pamac-manager",
        "Pavucontrol",
        "Spotify",
        "Timeset-gui",
        "VirtualBox Manager",
        "gnome-calculator",
        "kruler",
        "octopi",
        "qt5ct",
        "xfce4-taskmanager",
      },

      -- Note that the name property shown in xprop might be set slightly after creation of the client
      -- and the name shown there might not match defined rules here.
      name     = {
        "Taskmanager",
        "Taschenrechner",
        "BMenu"
        -- xev.
      },
      role     = {
        "AlarmWindow", -- Thunderbird's calendar.
        "ConfigManager", -- Thunderbird's about:config.
        "pop-up" -- e.g. Google Chrome's (detached) Developer Tools.
      }
    },
    properties = {
      floating = true
    }
  },

  -- opacity clients.
  {
    rule_any   = {
      instance = {
        "copyq",
      },
      class    = {
        "Alacritty",
      },

      -- Note that the name property shown in xprop might be set slightly after creation of the client
      -- and the name shown there might not match defined rules here.
      name     = {
        "Taskmanager",
        "Taschenrechner",
        "BMenu",
        "Rofi",
        "rofi"
        -- xev.
      },
      role     = {
        "pop-up" -- e.g. Google Chrome's (detached) Developer Tools.
      }
    },
    properties = {
      opacity = 0.7 }
  },

  -- Add titlebars to normal clients and dialogs
  {
    rule_any   = { type = { "normal", "dialog" } },
    properties = { titlebars_enabled = true }
  },
}
-- }}}
