---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by stira.
--- DateTime: 13.05.20 15:00
---

function runAsync(command)
  -- local command = "sleep 1; echo foo > /tmp/foo.txt"

  awful.spawn.easy_async_with_shell(command, function()
    awful.spawn.easy_async_with_shell("cat /tmp/foo.txt", function(out)
      mylabel.text = out
    end)
  end)
end
